// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: nodeapi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BucketCreateRequest) Reset() {
	*x = BucketCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketCreateRequest) ProtoMessage() {}

func (x *BucketCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketCreateRequest.ProtoReflect.Descriptor instead.
func (*BucketCreateRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{0}
}

func (x *BucketCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BucketCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BucketCreateResponse) Reset() {
	*x = BucketCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketCreateResponse) ProtoMessage() {}

func (x *BucketCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketCreateResponse.ProtoReflect.Descriptor instead.
func (*BucketCreateResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{1}
}

func (x *BucketCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BucketCreateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BucketViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
}

func (x *BucketViewRequest) Reset() {
	*x = BucketViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketViewRequest) ProtoMessage() {}

func (x *BucketViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketViewRequest.ProtoReflect.Descriptor instead.
func (*BucketViewRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{2}
}

func (x *BucketViewRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type BucketViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BucketViewResponse) Reset() {
	*x = BucketViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketViewResponse) ProtoMessage() {}

func (x *BucketViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketViewResponse.ProtoReflect.Descriptor instead.
func (*BucketViewResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{3}
}

func (x *BucketViewResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BucketViewResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketViewResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BucketListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BucketListRequest) Reset() {
	*x = BucketListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListRequest) ProtoMessage() {}

func (x *BucketListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListRequest.ProtoReflect.Descriptor instead.
func (*BucketListRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{4}
}

type BucketListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buckets []*BucketListResponse_Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
}

func (x *BucketListResponse) Reset() {
	*x = BucketListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListResponse) ProtoMessage() {}

func (x *BucketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListResponse.ProtoReflect.Descriptor instead.
func (*BucketListResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{5}
}

func (x *BucketListResponse) GetBuckets() []*BucketListResponse_Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type BucketDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BucketDeleteRequest) Reset() {
	*x = BucketDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDeleteRequest) ProtoMessage() {}

func (x *BucketDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDeleteRequest.ProtoReflect.Descriptor instead.
func (*BucketDeleteRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{6}
}

type BucketDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BucketDeleteResponse) Reset() {
	*x = BucketDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDeleteResponse) ProtoMessage() {}

func (x *BucketDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDeleteResponse.ProtoReflect.Descriptor instead.
func (*BucketDeleteResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{7}
}

type FileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{8}
}

type FileUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{9}
}

type FileUploadCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string                           `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	RootCid    string                           `protobuf:"bytes,2,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Chunks     []*FileUploadCreateRequest_Chunk `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Name       string                           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Size       int64                            `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileUploadCreateRequest) Reset() {
	*x = FileUploadCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCreateRequest) ProtoMessage() {}

func (x *FileUploadCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCreateRequest.ProtoReflect.Descriptor instead.
func (*FileUploadCreateRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{10}
}

func (x *FileUploadCreateRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *FileUploadCreateRequest) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FileUploadCreateRequest) GetChunks() []*FileUploadCreateRequest_Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FileUploadCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploadCreateRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileUploadCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkUploads []*FileUploadCreateResponse_ChunkUpload `protobuf:"bytes,1,rep,name=chunk_uploads,json=chunkUploads,proto3" json:"chunk_uploads,omitempty"`
}

func (x *FileUploadCreateResponse) Reset() {
	*x = FileUploadCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCreateResponse) ProtoMessage() {}

func (x *FileUploadCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCreateResponse.ProtoReflect.Descriptor instead.
func (*FileUploadCreateResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{11}
}

func (x *FileUploadCreateResponse) GetChunkUploads() []*FileUploadCreateResponse_ChunkUpload {
	if x != nil {
		return x.ChunkUploads
	}
	return nil
}

type FileChunkData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkCid string `protobuf:"bytes,2,opt,name=chunk_cid,json=chunkCid,proto3" json:"chunk_cid,omitempty"`
}

func (x *FileChunkData) Reset() {
	*x = FileChunkData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkData) ProtoMessage() {}

func (x *FileChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkData.ProtoReflect.Descriptor instead.
func (*FileChunkData) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{12}
}

func (x *FileChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunkData) GetChunkCid() string {
	if x != nil {
		return x.ChunkCid
	}
	return ""
}

type FileUploadChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUploadChunkResponse) Reset() {
	*x = FileUploadChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadChunkResponse) ProtoMessage() {}

func (x *FileUploadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadChunkResponse.ProtoReflect.Descriptor instead.
func (*FileUploadChunkResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{13}
}

type FileViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	FileName   string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *FileViewRequest) Reset() {
	*x = FileViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileViewRequest) ProtoMessage() {}

func (x *FileViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileViewRequest.ProtoReflect.Descriptor instead.
func (*FileViewRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{14}
}

func (x *FileViewRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *FileViewRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FileViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCid   string                 `protobuf:"bytes,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size      int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *FileViewResponse) Reset() {
	*x = FileViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileViewResponse) ProtoMessage() {}

func (x *FileViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileViewResponse.ProtoReflect.Descriptor instead.
func (*FileViewResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{15}
}

func (x *FileViewResponse) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FileViewResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileViewResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileViewResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{16}
}

type FileDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDownloadResponse) Reset() {
	*x = FileDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResponse) ProtoMessage() {}

func (x *FileDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{17}
}

type FileDownloadCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	RootCid    string `protobuf:"bytes,2,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
}

func (x *FileDownloadCreateRequest) Reset() {
	*x = FileDownloadCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateRequest) ProtoMessage() {}

func (x *FileDownloadCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{18}
}

func (x *FileDownloadCreateRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *FileDownloadCreateRequest) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

type FileDownloadCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunks []*FileDownloadCreateResponse_ChunkDownload `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *FileDownloadCreateResponse) Reset() {
	*x = FileDownloadCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateResponse) ProtoMessage() {}

func (x *FileDownloadCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{19}
}

func (x *FileDownloadCreateResponse) GetChunks() []*FileDownloadCreateResponse_ChunkDownload {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type FileDownloadCreateV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	FileName   string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *FileDownloadCreateV2Request) Reset() {
	*x = FileDownloadCreateV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateV2Request) ProtoMessage() {}

func (x *FileDownloadCreateV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateV2Request.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateV2Request) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{20}
}

func (x *FileDownloadCreateV2Request) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *FileDownloadCreateV2Request) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type FileDownloadCreateV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunks []*FileDownloadCreateV2Response_ChunkDownload `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *FileDownloadCreateV2Response) Reset() {
	*x = FileDownloadCreateV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateV2Response) ProtoMessage() {}

func (x *FileDownloadCreateV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateV2Response.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateV2Response) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{21}
}

func (x *FileDownloadCreateV2Response) GetChunks() []*FileDownloadCreateV2Response_ChunkDownload {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type FileDownloadChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkCid string `protobuf:"bytes,1,opt,name=chunk_cid,json=chunkCid,proto3" json:"chunk_cid,omitempty"`
}

func (x *FileDownloadChunkRequest) Reset() {
	*x = FileDownloadChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadChunkRequest) ProtoMessage() {}

func (x *FileDownloadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadChunkRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadChunkRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{22}
}

func (x *FileDownloadChunkRequest) GetChunkCid() string {
	if x != nil {
		return x.ChunkCid
	}
	return ""
}

type FileDownloadChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDownloadChunkResponse) Reset() {
	*x = FileDownloadChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadChunkResponse) ProtoMessage() {}

func (x *FileDownloadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadChunkResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadChunkResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{23}
}

type FileListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{24}
}

func (x *FileListRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*FileListResponse_File `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{25}
}

func (x *FileListResponse) GetList() []*FileListResponse_File {
	if x != nil {
		return x.List
	}
	return nil
}

type FileKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileKeysRequest) Reset() {
	*x = FileKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileKeysRequest) ProtoMessage() {}

func (x *FileKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileKeysRequest.ProtoReflect.Descriptor instead.
func (*FileKeysRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{26}
}

type FileKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileKeysResponse) Reset() {
	*x = FileKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileKeysResponse) ProtoMessage() {}

func (x *FileKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileKeysResponse.ProtoReflect.Descriptor instead.
func (*FileKeysResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{27}
}

type FileUpdateCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUpdateCreateRequest) Reset() {
	*x = FileUpdateCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUpdateCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdateCreateRequest) ProtoMessage() {}

func (x *FileUpdateCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdateCreateRequest.ProtoReflect.Descriptor instead.
func (*FileUpdateCreateRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{28}
}

type FileUpdateCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileUpdateCreateResponse) Reset() {
	*x = FileUpdateCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUpdateCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdateCreateResponse) ProtoMessage() {}

func (x *FileUpdateCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdateCreateResponse.ProtoReflect.Descriptor instead.
func (*FileUpdateCreateResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{29}
}

type FileDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDeleteRequest) Reset() {
	*x = FileDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteRequest) ProtoMessage() {}

func (x *FileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteRequest.ProtoReflect.Descriptor instead.
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{30}
}

type FileDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileDeleteResponse) Reset() {
	*x = FileDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteResponse) ProtoMessage() {}

func (x *FileDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteResponse.ProtoReflect.Descriptor instead.
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{31}
}

type BucketListResponse_Bucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *BucketListResponse_Bucket) Reset() {
	*x = BucketListResponse_Bucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketListResponse_Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListResponse_Bucket) ProtoMessage() {}

func (x *BucketListResponse_Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListResponse_Bucket.ProtoReflect.Descriptor instead.
func (*BucketListResponse_Bucket) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{5, 0}
}

func (x *BucketListResponse_Bucket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BucketListResponse_Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketListResponse_Bucket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FileUploadCreateRequest_Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid  string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileUploadCreateRequest_Chunk) Reset() {
	*x = FileUploadCreateRequest_Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadCreateRequest_Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCreateRequest_Chunk) ProtoMessage() {}

func (x *FileUploadCreateRequest_Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCreateRequest_Chunk.ProtoReflect.Descriptor instead.
func (*FileUploadCreateRequest_Chunk) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{10, 0}
}

func (x *FileUploadCreateRequest_Chunk) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *FileUploadCreateRequest_Chunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileUploadCreateResponse_ChunkUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size        uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	NodeAddress string `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeId      string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Permit      string `protobuf:"bytes,5,opt,name=permit,proto3" json:"permit,omitempty"`
}

func (x *FileUploadCreateResponse_ChunkUpload) Reset() {
	*x = FileUploadCreateResponse_ChunkUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadCreateResponse_ChunkUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCreateResponse_ChunkUpload) ProtoMessage() {}

func (x *FileUploadCreateResponse_ChunkUpload) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCreateResponse_ChunkUpload.ProtoReflect.Descriptor instead.
func (*FileUploadCreateResponse_ChunkUpload) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{11, 0}
}

func (x *FileUploadCreateResponse_ChunkUpload) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *FileUploadCreateResponse_ChunkUpload) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadCreateResponse_ChunkUpload) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *FileUploadCreateResponse_ChunkUpload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileUploadCreateResponse_ChunkUpload) GetPermit() string {
	if x != nil {
		return x.Permit
	}
	return ""
}

type FileDownloadCreateResponse_ChunkDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size        uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	NodeAddress string `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeId      string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Permit      string `protobuf:"bytes,5,opt,name=permit,proto3" json:"permit,omitempty"`
}

func (x *FileDownloadCreateResponse_ChunkDownload) Reset() {
	*x = FileDownloadCreateResponse_ChunkDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateResponse_ChunkDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateResponse_ChunkDownload) ProtoMessage() {}

func (x *FileDownloadCreateResponse_ChunkDownload) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateResponse_ChunkDownload.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateResponse_ChunkDownload) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{19, 0}
}

func (x *FileDownloadCreateResponse_ChunkDownload) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *FileDownloadCreateResponse_ChunkDownload) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileDownloadCreateResponse_ChunkDownload) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *FileDownloadCreateResponse_ChunkDownload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileDownloadCreateResponse_ChunkDownload) GetPermit() string {
	if x != nil {
		return x.Permit
	}
	return ""
}

type FileDownloadCreateV2Response_ChunkDownload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Size        uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	NodeAddress string `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeId      string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Permit      string `protobuf:"bytes,5,opt,name=permit,proto3" json:"permit,omitempty"`
}

func (x *FileDownloadCreateV2Response_ChunkDownload) Reset() {
	*x = FileDownloadCreateV2Response_ChunkDownload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDownloadCreateV2Response_ChunkDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadCreateV2Response_ChunkDownload) ProtoMessage() {}

func (x *FileDownloadCreateV2Response_ChunkDownload) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadCreateV2Response_ChunkDownload.ProtoReflect.Descriptor instead.
func (*FileDownloadCreateV2Response_ChunkDownload) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{21, 0}
}

func (x *FileDownloadCreateV2Response_ChunkDownload) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *FileDownloadCreateV2Response_ChunkDownload) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileDownloadCreateV2Response_ChunkDownload) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *FileDownloadCreateV2Response_ChunkDownload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FileDownloadCreateV2Response_ChunkDownload) GetPermit() string {
	if x != nil {
		return x.Permit
	}
	return ""
}

type FileListResponse_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCid   string                 `protobuf:"bytes,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size      int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *FileListResponse_File) Reset() {
	*x = FileListResponse_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeapi_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileListResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse_File) ProtoMessage() {}

func (x *FileListResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_nodeapi_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse_File.ProtoReflect.Descriptor instead.
func (*FileListResponse_File) Descriptor() ([]byte, []int) {
	return file_nodeapi_proto_rawDescGZIP(), []int{25, 0}
}

func (x *FileListResponse_File) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FileListResponse_File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileListResponse_File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileListResponse_File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_nodeapi_proto protoreflect.FileDescriptor

var file_nodeapi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x13, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x14, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x34, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a,
	0x12, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a, 0x67, 0x0a, 0x06,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xec, 0x01, 0x0a, 0x17, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52,
	0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x1a,
	0x2d, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xf8,
	0x01, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x0c, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x1a,
	0x87, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x22, 0x40, 0x0a, 0x0d, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65,
	0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x69,
	0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x57, 0x0a, 0x19, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x43,
	0x69, 0x64, 0x22, 0xf3, 0x01, 0x0a, 0x1a, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x1a, 0x89, 0x01, 0x0a,
	0x0d, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x22, 0x5b, 0x0a, 0x1b, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x32,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xf7, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x32, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x06, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x1a, 0x89, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x22,
	0x37, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x10, 0x46, 0x69,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x1a, 0x84, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x69, 0x6c,
	0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10,
	0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x86, 0x0a, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x50, 0x49, 0x12, 0x4d,
	0x0a, 0x0c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1a, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x0c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x20, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x20, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x41, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x32, 0x12,
	0x24, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x11, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x21, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x41, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x18, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x61,
	0x6b, 0x61, 0x76, 0x65, 0x2e, 0x61, 0x69, 0x2f, 0x61, 0x6b, 0x61, 0x76, 0x65, 0x2f, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodeapi_proto_rawDescOnce sync.Once
	file_nodeapi_proto_rawDescData = file_nodeapi_proto_rawDesc
)

func file_nodeapi_proto_rawDescGZIP() []byte {
	file_nodeapi_proto_rawDescOnce.Do(func() {
		file_nodeapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeapi_proto_rawDescData)
	})
	return file_nodeapi_proto_rawDescData
}

var file_nodeapi_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_nodeapi_proto_goTypes = []any{
	(*BucketCreateRequest)(nil),                        // 0: nodeapi.BucketCreateRequest
	(*BucketCreateResponse)(nil),                       // 1: nodeapi.BucketCreateResponse
	(*BucketViewRequest)(nil),                          // 2: nodeapi.BucketViewRequest
	(*BucketViewResponse)(nil),                         // 3: nodeapi.BucketViewResponse
	(*BucketListRequest)(nil),                          // 4: nodeapi.BucketListRequest
	(*BucketListResponse)(nil),                         // 5: nodeapi.BucketListResponse
	(*BucketDeleteRequest)(nil),                        // 6: nodeapi.BucketDeleteRequest
	(*BucketDeleteResponse)(nil),                       // 7: nodeapi.BucketDeleteResponse
	(*FileUploadRequest)(nil),                          // 8: nodeapi.FileUploadRequest
	(*FileUploadResponse)(nil),                         // 9: nodeapi.FileUploadResponse
	(*FileUploadCreateRequest)(nil),                    // 10: nodeapi.FileUploadCreateRequest
	(*FileUploadCreateResponse)(nil),                   // 11: nodeapi.FileUploadCreateResponse
	(*FileChunkData)(nil),                              // 12: nodeapi.FileChunkData
	(*FileUploadChunkResponse)(nil),                    // 13: nodeapi.FileUploadChunkResponse
	(*FileViewRequest)(nil),                            // 14: nodeapi.FileViewRequest
	(*FileViewResponse)(nil),                           // 15: nodeapi.FileViewResponse
	(*FileDownloadRequest)(nil),                        // 16: nodeapi.FileDownloadRequest
	(*FileDownloadResponse)(nil),                       // 17: nodeapi.FileDownloadResponse
	(*FileDownloadCreateRequest)(nil),                  // 18: nodeapi.FileDownloadCreateRequest
	(*FileDownloadCreateResponse)(nil),                 // 19: nodeapi.FileDownloadCreateResponse
	(*FileDownloadCreateV2Request)(nil),                // 20: nodeapi.FileDownloadCreateV2Request
	(*FileDownloadCreateV2Response)(nil),               // 21: nodeapi.FileDownloadCreateV2Response
	(*FileDownloadChunkRequest)(nil),                   // 22: nodeapi.FileDownloadChunkRequest
	(*FileDownloadChunkResponse)(nil),                  // 23: nodeapi.FileDownloadChunkResponse
	(*FileListRequest)(nil),                            // 24: nodeapi.FileListRequest
	(*FileListResponse)(nil),                           // 25: nodeapi.FileListResponse
	(*FileKeysRequest)(nil),                            // 26: nodeapi.FileKeysRequest
	(*FileKeysResponse)(nil),                           // 27: nodeapi.FileKeysResponse
	(*FileUpdateCreateRequest)(nil),                    // 28: nodeapi.FileUpdateCreateRequest
	(*FileUpdateCreateResponse)(nil),                   // 29: nodeapi.FileUpdateCreateResponse
	(*FileDeleteRequest)(nil),                          // 30: nodeapi.FileDeleteRequest
	(*FileDeleteResponse)(nil),                         // 31: nodeapi.FileDeleteResponse
	(*BucketListResponse_Bucket)(nil),                  // 32: nodeapi.BucketListResponse.Bucket
	(*FileUploadCreateRequest_Chunk)(nil),              // 33: nodeapi.FileUploadCreateRequest.Chunk
	(*FileUploadCreateResponse_ChunkUpload)(nil),       // 34: nodeapi.FileUploadCreateResponse.ChunkUpload
	(*FileDownloadCreateResponse_ChunkDownload)(nil),   // 35: nodeapi.FileDownloadCreateResponse.ChunkDownload
	(*FileDownloadCreateV2Response_ChunkDownload)(nil), // 36: nodeapi.FileDownloadCreateV2Response.ChunkDownload
	(*FileListResponse_File)(nil),                      // 37: nodeapi.FileListResponse.File
	(*timestamppb.Timestamp)(nil),                      // 38: google.protobuf.Timestamp
}
var file_nodeapi_proto_depIdxs = []int32{
	38, // 0: nodeapi.BucketCreateResponse.created_at:type_name -> google.protobuf.Timestamp
	38, // 1: nodeapi.BucketViewResponse.created_at:type_name -> google.protobuf.Timestamp
	32, // 2: nodeapi.BucketListResponse.buckets:type_name -> nodeapi.BucketListResponse.Bucket
	33, // 3: nodeapi.FileUploadCreateRequest.chunks:type_name -> nodeapi.FileUploadCreateRequest.Chunk
	34, // 4: nodeapi.FileUploadCreateResponse.chunk_uploads:type_name -> nodeapi.FileUploadCreateResponse.ChunkUpload
	38, // 5: nodeapi.FileViewResponse.created_at:type_name -> google.protobuf.Timestamp
	35, // 6: nodeapi.FileDownloadCreateResponse.chunks:type_name -> nodeapi.FileDownloadCreateResponse.ChunkDownload
	36, // 7: nodeapi.FileDownloadCreateV2Response.chunks:type_name -> nodeapi.FileDownloadCreateV2Response.ChunkDownload
	37, // 8: nodeapi.FileListResponse.list:type_name -> nodeapi.FileListResponse.File
	38, // 9: nodeapi.BucketListResponse.Bucket.created_at:type_name -> google.protobuf.Timestamp
	38, // 10: nodeapi.FileListResponse.File.created_at:type_name -> google.protobuf.Timestamp
	0,  // 11: nodeapi.NodeAPI.BucketCreate:input_type -> nodeapi.BucketCreateRequest
	2,  // 12: nodeapi.NodeAPI.BucketView:input_type -> nodeapi.BucketViewRequest
	4,  // 13: nodeapi.NodeAPI.BucketList:input_type -> nodeapi.BucketListRequest
	6,  // 14: nodeapi.NodeAPI.BucketDelete:input_type -> nodeapi.BucketDeleteRequest
	10, // 15: nodeapi.NodeAPI.FileUploadCreate:input_type -> nodeapi.FileUploadCreateRequest
	8,  // 16: nodeapi.NodeAPI.FileUpload:input_type -> nodeapi.FileUploadRequest
	12, // 17: nodeapi.NodeAPI.FileUploadChunk:input_type -> nodeapi.FileChunkData
	14, // 18: nodeapi.NodeAPI.FileView:input_type -> nodeapi.FileViewRequest
	18, // 19: nodeapi.NodeAPI.FileDownloadCreate:input_type -> nodeapi.FileDownloadCreateRequest
	20, // 20: nodeapi.NodeAPI.FileDownloadCreateV2:input_type -> nodeapi.FileDownloadCreateV2Request
	16, // 21: nodeapi.NodeAPI.FileDownload:input_type -> nodeapi.FileDownloadRequest
	22, // 22: nodeapi.NodeAPI.FileDownloadChunk:input_type -> nodeapi.FileDownloadChunkRequest
	24, // 23: nodeapi.NodeAPI.FileList:input_type -> nodeapi.FileListRequest
	26, // 24: nodeapi.NodeAPI.FileKeys:input_type -> nodeapi.FileKeysRequest
	28, // 25: nodeapi.NodeAPI.FileUpdateCreate:input_type -> nodeapi.FileUpdateCreateRequest
	30, // 26: nodeapi.NodeAPI.FileDelete:input_type -> nodeapi.FileDeleteRequest
	1,  // 27: nodeapi.NodeAPI.BucketCreate:output_type -> nodeapi.BucketCreateResponse
	3,  // 28: nodeapi.NodeAPI.BucketView:output_type -> nodeapi.BucketViewResponse
	5,  // 29: nodeapi.NodeAPI.BucketList:output_type -> nodeapi.BucketListResponse
	7,  // 30: nodeapi.NodeAPI.BucketDelete:output_type -> nodeapi.BucketDeleteResponse
	11, // 31: nodeapi.NodeAPI.FileUploadCreate:output_type -> nodeapi.FileUploadCreateResponse
	9,  // 32: nodeapi.NodeAPI.FileUpload:output_type -> nodeapi.FileUploadResponse
	13, // 33: nodeapi.NodeAPI.FileUploadChunk:output_type -> nodeapi.FileUploadChunkResponse
	15, // 34: nodeapi.NodeAPI.FileView:output_type -> nodeapi.FileViewResponse
	19, // 35: nodeapi.NodeAPI.FileDownloadCreate:output_type -> nodeapi.FileDownloadCreateResponse
	21, // 36: nodeapi.NodeAPI.FileDownloadCreateV2:output_type -> nodeapi.FileDownloadCreateV2Response
	17, // 37: nodeapi.NodeAPI.FileDownload:output_type -> nodeapi.FileDownloadResponse
	12, // 38: nodeapi.NodeAPI.FileDownloadChunk:output_type -> nodeapi.FileChunkData
	25, // 39: nodeapi.NodeAPI.FileList:output_type -> nodeapi.FileListResponse
	27, // 40: nodeapi.NodeAPI.FileKeys:output_type -> nodeapi.FileKeysResponse
	29, // 41: nodeapi.NodeAPI.FileUpdateCreate:output_type -> nodeapi.FileUpdateCreateResponse
	31, // 42: nodeapi.NodeAPI.FileDelete:output_type -> nodeapi.FileDeleteResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_nodeapi_proto_init() }
func file_nodeapi_proto_init() {
	if File_nodeapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodeapi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BucketCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BucketCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BucketViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BucketViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BucketListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BucketListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*BucketDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BucketDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*FileChunkData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*FileViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*FileViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*FileListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*FileListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*FileKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*FileKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*FileUpdateCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*FileUpdateCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*FileDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*FileDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*BucketListResponse_Bucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadCreateRequest_Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*FileUploadCreateResponse_ChunkUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateResponse_ChunkDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[36].Exporter = func(v any, i int) any {
			switch v := v.(*FileDownloadCreateV2Response_ChunkDownload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeapi_proto_msgTypes[37].Exporter = func(v any, i int) any {
			switch v := v.(*FileListResponse_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeapi_proto_goTypes,
		DependencyIndexes: file_nodeapi_proto_depIdxs,
		MessageInfos:      file_nodeapi_proto_msgTypes,
	}.Build()
	File_nodeapi_proto = out.File
	file_nodeapi_proto_rawDesc = nil
	file_nodeapi_proto_goTypes = nil
	file_nodeapi_proto_depIdxs = nil
}
